### ISSUE TITLE
Add featured images to tutorials

### ISSUE THREAD

**Issue by vragosta** [vragosta/dracobit.io#11]
Its that simple, add images in the backend.

However, lets hook it into the right column on the tutorials page.  Lets rap about it whenever you get images up.

**Comment by frankieb137** [comment]
Images are up on the backend

**Comment by vragosta** [comment]
ideally we want to display the images at the top on the right column.

**Comment by vragosta** [comment]
going to create api before we do this, however you can still hardcode this in for now if you would like.
