### ISSUE TITLE
Create community custom post type

### ISSUE THREAD

**Issue by frankieb137** [vragosta/dracobit.io#160]
The custom post type needs:
- [x] A custom API endpoint
- [x] To hit the community and user API endpoints when a new user joins
- [x]  To have custom meta fields for:
    - [x] Members
    - [x] Moderators
    - [x] Owners
    - [x] Community Tier
    - [x] Chapters
    - [x] Tutorials

**Comment by vragosta** [comment]
...and so it begins...
