### ISSUE TITLE
Intern Task One - HTML Grid

### ISSUE THREAD

**Issue by blandvogt** [vragosta/dracobit.io#173]
Create a row in HTML. The first `3` blocks should be `red`, the next `6` blocks should be `black`, and the last `3` blocks should be `blue`. 

#### First ( 1200px + ):
- [x] `7` blocks in `red`
- [x] `3` blocks in `black`
- [x] `2` blocks in `blue`

#### Second ( 1199px - 992px ):
- [x] `2` blocks in `red` 
- [x] `8` blocks in `black` 
- [x] `2` blocks in `blue`

#### Third ( 991px - 768px ):
- [x] `8` blocks in `red`
- [x] `2` blocks in `black`
- [x] `2` blocks in `blue`

#### Fourth ( 768px - ):
- [x] `2` blocks in `red` 
- [x] `1` blocks in `black`
- [x] `9` blocks in `blue`

**Comment by vragosta** [comment]
@blandvogt I updated the issue to have checkboxes in the list, the bullet points was exactly what I had asked for so you did not do this wrong.

This way you can keep track of what subtasks of the issue have been completed.
