### ISSUE TITLE
Accomodate left column styles on tutorial page template

### ISSUE THREAD

**Issue by vragosta** [vragosta/dracobit.io#29]
Since I had to shrink the column to accomodate the sidebar, make the font-sizes of the title and tagline smaller in style.css, try to make them on one line if pos.

**Comment by frankieb137** [comment]
Will tweak styles if need be

**Comment by vragosta** [comment]
lets try this:

#tutorials-page-container {
    width: 1400px;
}

then, make the left column go from ( col-sm-2 ) to ( col-sm-3 ) [ of course do for all media sizes ] and shrink the center column from 7 to 6.

Also, remove the text -align center on .list-group-item. We want to keep everything left justified, and a float right on the version tag.
